swiftmailer:
    spool: { type: 'memory' }
    transport:  smtp
    host:       '%env(MAIL_HOST)%'
    username:   '%env(MAIL_USER)%'
    password:   '%env(MAIL_PWD)%'
    port:       587
    encryption: tls

